local inventors = {
"Vitaly Abalakov",
"Ernst Karl Abbe",
"Hovannes Adamian",
"Samuel W. Alderson",
"Alexandre Alexeieff",
"Rostislav Alexeyev",
"Randi Altschul",
"Bruce Ames",
"Giovanni Battista Amici",
"Mary Anderson",
"Momofuku Ando",
"Hal Anger",
"Anders Knutsson Ångström",
"Ottomar Anschütz",
"Hermann Anschütz-Kaempfe",
"Virginia Apgar",
"Nicolas Appert",
"Archimedes",
"Guido of Arezzo",
"Ami Argand",
"William George Armstrong",
"Neil Arnott",
"Joseph Aspdin",
"John Vincent Atanasoff",
"Charles Babbage",
"Tabitha Babbit",
"Victor Babeș",
"Leo Baekeland",
"Ralph H. Baer",
"Adolf von Baeyer",
"John Logie Baird",
"Abi Bakr of Isfahan",
"George Ballas",
"Vladimir Baranov-Rossine",
"John Barber",
"John Bardeen",
"Vladimir Barmin",
"Anthony R. Barringer",
"Earl W. Bascom",
"Nikolay Basov",
"Émile Baudot",
"Eugen Baumann",
"Trevor Baylis",
"Maria Beasley",
"Francis Beaufort",
"Arnold O. Beckman",
"Vladimir Bekhterev",
"Josip Belušić",
"Alexander Graham Bell",
"Nikolay Benardos",
"Ruth R. Benerito",
"Miriam Benjamin",
"William R. Bennett, Jr.",
"Melitta Bentz",
"Karl Benz",
"Hans Berger",
"Friedrich Bergius",
"Emile Berliner",
"Tim Berners-Lee",
"Marcellin Berthelot",
"Max Bielschowsky",
"Alfred Binet",
"Lucio Bini",
"Gerd Binnig",
"Clarence Birdseye",
"Laszlo Biro",
"Thor Bjørklund",
"J. Stuart Blackton",
"Otto Blathy",
"John Blenkinsop",
"Charles K. Bliss",
"Katharine B. Blodgett",
"Alan Blumlein",
"David Boggs",
"Nils Bohlin",
"Charlie Booth",
"Sam Born",
"Jagdish Chandra Bose",
"Matthew Piers Watt Boulton",
"Seth Boyden",
"Herbert Boyer",
"Willard Boyle",
"Hugh Bradner",
"Louis Braille",
"Jacques E. Brandenberger",
"Édouard Branly",
"Charles F. Brannock",
"Walter Houser Brattain",
"Karl Ferdinand Braun",
"Stanislav Brebera",
"David Brewster",
"Rachel Fuller Brown",
"William C. Brown",
"Marie Van Brittan Brown",
"Friedrich Wilhelm Gustav Bruhn",
"Nikolay Brusentsov",
"Dudley Allen Buck",
"Edwin Beard Budding",
"Gersh Budker",
"Robert Bunsen",
"Henry Burden",
"Robert Cailliau",
"Nicholas Callan",
"Tullio Campagnolo",
"Charles Cantor",
"Mario Ramberg Capecchi",
"Arturo Caprotti",
"Gerolamo Cardano",
"Chester Carlson",
"Wallace Carothers",
"Antonio Benedetto Carpano",
"Giovanni Caselli",
"George Cayley",
"Anders Celsius",
"Vint Cerf",
"Ugo Cerletti",
"Charles Chamberland",
"Min Chueh Chang",
"Thomas Chang",
"Emmett Chapman",
"Claude Chappe",
"David Chaum",
"Vladimir Chelomey",
"Pavel Cherenkov",
"Evgeniy Chertovsky",
"Ward Christensen",
"Ole Kirk Christiansen",
"Samuel Hunter Christie",
"Juan de la Cierva",
"Leland Clark",
"Georges Claude",
"Henri Marie Coandă",
"Josephine Cochrane",
"Christopher Cockerell",
"Aeneas Coffey",
"Sir Henry Cole",
"Samuel Colt",
"George Constantinescu",
"Albert Coons",
"Martin Cooper",
"Harry Coover",
"Lloyd Groff Copeman",
"Cornelis Corneliszoon",
"Alexander Coucoulas",
"Wallace H. Coulter",
"Jacques Cousteau",
"John Higson Cover, Jr.",
"William Crookes",
"Bartolomeo Cristofori",
"S. Scott Crump",
"Nicolas-Joseph Cugnot",
"William Cullen",
"Jan Czochralski",
"Nils Gustaf Dalén",
"John Frederic Daniell",
"Corradino D'Ascanio",
"Leonardo da Vinci",
"Jacob Davis",
"Humphry Davy",
"Joseph Day",
"Lee DeForest",
"Yuri Nikolaevich Denisyuk",
"Robert H. Dennard",
"Miksa Deri",
"James Dewar",
"Aleksandr Dianin",
"William Kennedy Laurie Dickson",
"Philip Diehl",
"Rudolf Diesel",
"William H. Dobelle",
"Johann Wolfgang Döbereiner",
"Toshitada Doi",
"Ray Dolby",
"Gene Dolgoff",
"Mikhail Dolivo-Dobrovolsky",
"Marion O'Brien Donovan",
"Hub van Doorne",
"John Thompson Dorrance",
"Amanda Minnie Douglas",
"Charles Dow",
"Mulalo Doyoyo",
"Anastase Dragomir",
"Karl Drais",
"Richard Drew",
"John Boyd Dunlop",
"Cyril Duquet",
"Alexey Dushkin",
"James Dyson",
"George Eastman",
"J. Presper Eckert",
"Thomas Alva Edison",
"Pehr Victor Edman",
"Sir Robert Geoffrey Edwards",
"Ellen Eglin",
"Brendan Eich",
"Willem Einthoven",
"Benjamin Eisenstadt",
"Paul Eisler",
"Giorgi Eliava",
"Ivan Elmanov",
"Rune Elmqvist",
"John Haven Emerson",
"Douglas Engelbart",
"John Ericsson",
"Lars Magnus Ericsson",
"Emil Erlenmeyer",
"Sir Martin John Evans",
"Ole Evinrude",
"Charles Fabry",
"Samuel Face",
"Federico Faggin",
"Daniel Gabriel Fahrenheit",
"Michael Faraday",
"Johann Maria Farina",
"Myra Juliet Farrell",
"Philo Farnsworth",
"Muhammad al-Fazari",
"John Bennett Fenn",
"Henry John Horstman Fenton",
"James Fergason",
"Enrico Fermi",
"Humberto Fernández Morán",
"Michele Ferrero",
"Bran Ferren",
"Reginald Fessenden",
"Robert Feulgen",
"Adolf Gaston Eugen Fick",
"Abbas Ibn Firnas",
"Artur Fischer",
"Franz Joseph Emil Fischer",
"Franz Joseph Emil Fischer",
"Gerhard Fischer",
"Paul C. Fisher",
"Alexander Fleming",
"John Ambrose Fleming",
"Sandford Fleming",
"Nicolas Florine",
"Tommy Flowers",
"Thomas J. Fogarty",
"Enrico Forlanini",
"Eric Fossum",
"Jean Bernard Léon Foucault",
"Benoît Fourneyron",
"John Fowler",
"Benjamin Franklin",
"Herman Frasch",
"Ian Hector Frazer",
"Augustin-Jean Fresnel",
"William Friese-Greene",
"Julius Fromm",
"Arthur Fry",
"Buckminster Fuller",
"Robert Fulton",
"Ivan Fyodorov",
"Svyatoslav Fyodorov",
"Vladimir Fyodorov",
"Dennis Gabor",
"Boris Borisovich Galitzine",
"Joseph G. Gall",
"Alfred William Gallagher",
"Dmitri Garbuzov",
"Elmer R. Gates",
"Richard J. Gatling",
"Georgy Gause",
"E. K. Gauzen",
"Norman Gaylord",
"Karl-Hermann Geib",
"Hans Wilhelm Geiger",
"Andrey Geim",
"Nestor Genko",
"Christoph Gerber",
"Friedrich Clemens Gerke",
"David Gestetner",
"Alberto Gianni",
"John Heysham Gibbon",
"Gustav Giemsa",
"Adolph Giesl-Gieslingen",
"Henri Giffard",
"Donald A. Glaser",
"C. W. Fuller",
"Valentyn Glushko",
"Heinrich Göbel",
"Leonid Gobyato",
"Robert Goddard",
"Sam Golden",
"Peter Carl Goldmark",
"Camillo Golgi",
"György Gömöri",
"Charles Goodyear",
"Robert W. Gore",
"Igor Gorynin",
"James Gosling",
"Gordon Gould",
"Richard Hall Gower",
"Boris Grabovsky",
"Bette Nesmith Graham",
"Hans Christian Gram",
"Zénobe Gramme",
"Temple Grandin",
"Michael Grätzel",
"James Henry Greathead",
"Chester Greenwood",
"James Gregory",
"Charles Leiper Grigg",
"William Robert Grove",
"Gustav Guanella",
"Otto von Guericke",
"Mikhail Gurevich",
"Goldsworthy Gurney",
"Bartolomeu de Gusmão",
"Johann Gutenberg",
"Samuel Guthrie",
"Fritz Haber",
"John Hadley",
"Waldemar Haffkine",
"Gunther von Hagens",
"Charles Hall",
"Robert N. Hall",
"Tracy Hall",
"Richard Hamming",
"John Hays Hammond, Jr.",
"Ruth Handler",
"James Hargreaves",
"John Harington",
"William Snow Harris",
"John Harrison",
"Ross Granville Harrison",
"Kazuo Hashimoto",
"Victor Hasselblad",
"Ibn al-Haytham",
"Zheng He",
"George H. Heilmeier",
"Henry Heimlich",
"Robert A. Heinlein",
"Jozef Karol Hell",
"Rudolf Hell",
"Hermann von Helmholtz",
"Greg Henderson",
"Zhang Heng",
"Beulah Louise Henry",
"Charles H. Henry",
"Joseph Henry",
"Félix d'Herelle",
"Heron",
"John Herschel",
"Harry Houdini",
"Heinrich Hertz",
"Ephraim Hertzano",
"Lasse Hessel",
"George de Hevesy",
"Ronald Price Hickman",
"Rowland Hill",
"Maurice Hilleman",
"Tanaka Hisashige",
"Ted Hoff",
"Felix Hoffmann",
"Albert Hofmann",
"Kotaro Honda",
"Huang Hongjia",
"Herman Hollerith",
"Nick Holonyak",
"Norman Holter",
"Robert Hooke",
"Erna Schneider Hoover",
"Grace Murray Hopper",
"Frank Hornby",
"Jimmy Hotz",
"Royal Earl House",
"Coenraad Johannes van Houten",
"Elias Howe",
"David Edward Hughes",
"Chuck Hull",
"Miller Reese Hutchison",
"Christiaan Huygens",
"John Wesley Hyatt",
"Gavriil Ilizarov",
"Mamoru Imura",
"Daisuke Inoue",
"János Irinyi",
"Ub Iwerks",
"Moritz von Jacobi",
"Rudolf Jaenisch",
"Karl Guthe Jansky",
"Karl Jatho",
"Ali Javan",
"Al-Jazari",
"Ibn Al-Jazzar",
"Ányos Jedlik",
"Alec John Jeffreys",
"Charles Francis Jenkins",
"Steve Jobs",
"Amos Edward Joel, Jr.",
"Carl Edvard Johansson",
"Johan Petter Johansson",
"Reynold B. Johnson",
"Philipp von Jolly",
"Scott A. Jones",
"Tom Parry Jones",
"Assen Jordanoff",
"Anatol Josepho",
"Marjorie Joyner",
"Whitcomb Judson",
"Percy Lavon Julian",
"Ma Jun",
"Mikhail Kalashnikov",
"Bob Kahn",
"Dawon Kahng",
"Dean Kamen",
"Heike Kamerlingh Onnes",
"Nikolay Kamov",
"Pyotr Kapitsa",
"Georgii Karpechenko",
"Jamshīd al-Kāshī",
"Yevgeny Kaspersky",
"Andrew Kay",
"Adolphe Kégresse",
"Carl D. Keith",
"Mstislav Keldysh",
"John Harvey Kellogg",
"John G. Kemeny",
"Alexander Kemurdzhian",
"Mary Beatrice Davidson Kenner",
"William Saville-Kent",
"Kerim Kerimov",
"Charles F. Kettering",
"Fazlur Khan",
"Yulii Khariton",
"Anatoly Kharlampiev",
"Al-Khazini",
"Konstantin Khrenov",
"Abu-Mahmud al-Khujandi",
"Muhammad ibn Mūsā al-Khwārizmī",
"Marcel Kiepach",
"Erhard Kietz",
"Jack Kilby",
"Al-Kindi",
"Petrus Jacobus Kipp",
"Steve Kirsch",
"Fritz Klatte",
"Yves Klein",
"Margaret E. Knight",
"Tom Knight",
"Ivan Knunyants",
"Robert Koch",
"Willem Johan Kolff",
"Rudolf Kompfner",
"Konstantin Konstantinov",
"Sergey Korolyov",
"Nikolai Korotkov",
"Semen Korsakov",
"Mikhail Koshkin",
"Ognjeslav Kostović",
"Gleb Kotelnikov",
"William Justin Kroll",
"Alexei Krylov",
"Ivan Kulibin",
"Shen Kuo",
"Igor Kurchatov",
"Thomas E. Kurtz",
"Raymond Kurzweil",
"Ken Kutaragi",
"Stephanie Kwolek",
"John Howard Kyan",
"Dmitry Lachinov",
"René Laennec",
"Georges Lakhovsky",
"Hedy Lamarr",
"Edwin H. Land",
"Samuel P. Langley",
"Alexander Nikolayevich Lodygin",
"Irving Langmuir",
"Norm Larsen",
"Lewis Latimer",
"Gustav de Laval",
"Semyon Lavochkin",
"John Bennet Lawes",
"Ernest Orlando Lawrence",
"Nikolai Lebedenko",
"Sergei Lebedev",
"William Lee",
"Antoni van Leeuwenhoek",
"Jerome H. Lemelson",
"Jean-Joseph Etienne Lenoir",
"Giacomo da Lentini",
"R. G. LeTourneau",
"Rasmus Lerdorf",
"Willard Frank Libby",
"Justus von Liebig",
"Hon Lik",
"Otto Lilienthal",
"Lin Yutang",
"Charles Lindbergh",
"Frans Wilhelm Lindqvist",
"Carl Linnaeus",
"Hans Lippershey",
"Jonas Ferdinand Gabriel Lippmann",
"William Howard Livens",
"Eduard Locher",
"Alexander Lodygin",
"Mikhail Lomonosov",
"Yury Lomonosov",
"Aleksandr Loran",
"Oleg Losev",
"Antoine Louis",
"Archibald Low",
"Ed Lowe",
"Gleb Lozino-Lozinskiy",
"Ignacy Łukasiewicz",
"Auguste and Louis Lumière",
"Cai Lun",
"Giovanni Luppis or Ivan Vukić",
"Richard F. Lyon",
"Arkhip Lyulka",
"Charles Macintosh",
"Theodore Maiman",
"Ahmed Majan",
"Aleksandr Makarov",
"Stepan Makarov",
"Victor Makeev",
"Nestor Makhno",
"Dmitri Dmitrievich Maksutov",
"Annie Malone",
"Sergey Malyutin",
"Al-Ma'mun",
"Boris Mamyrin",
"George William Manby",
"Joy Mangano",
"Charles Mantoux",
"Guglielmo Marconi",
"Gheorghe Marinescu",
"Sylvester Marsh",
"Konosuke Matsushita",
"Taqi al-Din Muhammad ibn Ma'ruf",
"John Landis Mason",
"Fujio Masuoka",
"John W. Mauchly",
"Henry Maudslay",
"Hiram Maxim",
"James Clerk Maxwell",
"Stanley Mazor",
"John Loudon McAdam",
"Elijah McCoy",
"Nicholas McKay, Sr.",
"James McLurkin",
"Ilya Ilyich Mechnikov",
"Hippolyte Mège-Mouriès",
"Mordecai Meirowitz",
"Dmitri Mendeleev",
"George de Mestral",
"Robert Metcalfe",
"Antonio Meucci",
"Édouard Michelin",
"Anthony Michell",
"Artem Mikoyan",
"Alexander Mikulin",
"Mikhail Mil",
"David L. Mills",
"Marvin Minsky",
"Tokushichi Mishima",
"Pavel Molchanov",
"Jules Montenier",
"Montgolfier brothers",
"John J. Montgomery",
"Narcis Monturiol i Estarriol",
"Robert Moog",
"John J. Mooney",
"Roland Moreno",
"Samuel Morey",
"Garrett A. Morgan",
"Alexander Morozov",
"Walter Frederick Morrison",
"William Morrison",
"Samuel Morse",
"Sergei Ivanovich Mosin",
"Vera Mukhina",
"Kary Mullis",
"Fe del Mundo",
"Colin Murdoch",
"William Murdoch",
"Jozef Murgas",
"Evgeny Murzin",
"Elon Musk",
"Pieter van Musschenbroek",
"Walton Musser",
"Eadweard Muybridge",
"Georgi Nadjakov",
"Alexander Nadiradze",
"Nagai Nagayoshi",
"James Naismith",
"Yoshiro Nakamatsu",
"Shuji Nakamura",
"John Napier",
"Andrey Nartov",
"James Nasmyth",
"Giulio Natta",
"Nebuchadrezzar II",
"Erwin Neher",
"Ted Nelson",
"Sergey Nepobedimiy",
"Karl Nessler",
"Bernard de Neumann",
"John von Neumann",
"Isaac Newton",
"Miguel Nicolelis",
"Joseph Nicephore Niépce",
"Nikolai Nikitin",
"Paul Gottlieb Nipkow",
"Jun-Ichi Nishizawa",
"Alfred Nobel",
"Ludvig Nobel",
"Emmy Noether",
"Jean-Antoine Nollet",
"Wilhelm Normann",
"Carl Richard Nyberg",
"Aaron D. O'Connell",
"Theophil Wilgodt Odhner",
"Paul Offit",
"Jarkko Oikarinen",
"Katsuhiko Okamoto",
"Ransom Eli Olds",
"Lucien Olivier",
"Gerard K. O'Neill",
"J. Robert Oppenheimer",
"Edward Otho Cresap Ord, II",
"Hans Christian Ørsted",
"Elisha Otis",
"William Oughtred",
"Arogyaswami Paulraj",
"Antonio Pacinotti",
"Larry Page",
"William Painter",
"Alexey Pajitnov",
"Julio Palmaz",
"Helge Palmcrantz",
"Daniel David Palmer",
"Luigi Palmieri",
"Frank Pantridge",
"Georgios Papanikolaou",
"Philip M. Parker",
"Alexander Parkes",
"Forrest Parry",
"Charles Algernon Parsons",
"Spede Pasanen",
"Blaise Pascal",
"Gustaf Erik Pasch",
"Dimitar Paskov",
"C. Kumar N. Patel",
"Les Paul",
"Andreas Pavel",
"Ivan Pavlov",
"Floyd Paxton",
"John Pemberton",
"Slavoljub Eduard Penkala",
"William Henry Perkin",
"Henry Perky",
"Alfred Perot",
"Stephen Perry",
"Aurel Persu",
"Vladimir Petlyakov",
"Julius Richard Petri",
"Peter Petroff",
"Fritz Pfleumer",
"Auguste Piccard",
"Gregory Goodwin Pincus",
"Nikolay Ivanovich Pirogov",
"Fyodor Pirotsky",
"Arthur Pitney",
"Hippolyte Pixii",
"Joseph Plateau",
"Baltzar von Platen",
"James Leonard Plimpton",
"Ivan Plotnikov",
"Roy Plunkett",
"Petrache Poenaru",
"Christopher Polhem",
"Nikolai Polikarpov",
"Eugene Polley",
"Ivan Polzunov",
"Mikhail Pomortsev",
"Olivia Poole",
"Alexander Popov",
"Nikolay Popov",
"Josef Popper",
"Aleksandr Porokhovschikov",
"Ignazio Porro",
"Valdemar Poulsen",
"Joseph Priestley",
"Alexander Procofieff de Seversky",
"Alexander Prokhorov",
"Petro Prokopovych",
"Sergey Prokudin-Gorsky",
"Mark Publicover",
"George Pullman",
"Michael I. Pupin",
"Tivadar Puskas",
"Calvin Quate",
"Adolphe Quetelet",
"Jacob Rabinow",
"John Goffe Rand",
"Muhammad ibn Zakarīya Rāzi",
"Alec Reeves",
"Karl von Reichenbach",
"Tadeus Reichstein",
"Ira Remsen",
"Ralf Reski",
"Josef Ressel",
"Ri Sung-gi",
"Charles Francis Richter",
"Adolph Rickenbacker",
"Hyman George Rickover",
"Niklaus Riggenbach",
"Dennis Ritchie",
"Gilles de Roberval",
"John Roebuck",
"Francis Rogallo",
"Heinrich Rohrer",
"Peter I the Great",
"Wilhelm Conrad Röntgen",
"Ida Rosenthal",
"Sidney Rosenthal",
"Eugene Roshal",
"Boris Rosing",
"Guido van Rossum",
"Jean-François Pilâtre de Rozier",
"Ernő Rubik",
"Ernst Ruska",
"Albert Bruce Sabin",
"Alexander Sablukov",
"Şerafeddin Sabuncuoğlu",
"Gilles Saint-Hilaire",
"Andrei Sakharov",
"Jonas Edward Salk",
"Franz San Galli",
"Frederick Sanger",
"Larry Sanger",
"Yoshiyuki Sankai",
"Alberto Santos-Dumont",
"Arthur William Savage",
"Thomas Savery",
"Adolphe Sax",
"Vincent Joseph Schaefer",
"Bela Schick",
"Hugo Schiff",
"Pavel Schilling",
"Gilmore Schjeldahl",
"Hubert Schlafly",
"Wilhelm Schlenk",
"Bernhard Schmidt",
"Otto Schmitt",
"Christian Schnabel",
"Kees A. Schouhamer Immink",
"August Schrader",
"David Schwarz",
"Raymond Scott",
"Marc Seguin",
"Hanaoka Seishū",
"Ted Selker",
"Sennacherib",
"Léon Serpollet",
"Iwan Serrurier",
"Mark Serrurier",
"Gerhard Sessler",
"Guy Severin",
"Ed Seymour",
"Leonty Shamshurenkov",
"Ibn al-Shatir",
"Bi Sheng",
"Murasaki Shikibu",
"Pyotr Shilovsky",
"Masatoshi Shima",
"Fathullah Shirazi",
"Joseph Shivers",
"William Bradford Shockley",
"Henry Shrapnel",
"Vladimir Shukhov",
"Sheikh Muszaphar Shukor",
"Augustus Siebe",
"Sir William Siemens",
"Werner von Siemens",
"Al-Sijzi",
"Igor Sikorsky",
"Bernard Silver",
"Kia Silverbrook",
"Vladimir Simonov",
"Charles Simonyi",
"Ibn Sina",
"Isaac Singer",
"B. F. Skinner",
"Nikolay Slavyanov",
"Alexander Smakula",
"Michael Smith",
"Oliver Smithies",
"Yefim Smolin",
"Friedrich Soennecken",
"Su Song",
"Marin Soljačić",
"Edwin Southern",
"Alfred P. Southwick",
"Igor Spassky",
"Percy Spencer",
"Elmer Ambrose Sperry",
"Lyman Spitzer",
"Bhargav Sri Prakash",
"Ladislas Starevich",
"Gary Starkweather",
"Boris Stechkin",
"George Stephenson",
"Simon Stevin",
"Andreas Stihl",
"Reverend Dr Robert Stirling",
"Aurel Stodola",
"Aleksandr Stoletov",
"Levi Strauss",
"John Stringfellow",
"Bjarne Stroustrup",
"Almon Strowger",
"Emil Strub",
"Abd al-Rahman al-Sufi",
"Kyota Sugimoto",
"Mutsuo Sugiura",
"Pavel Sukhoi",
"Simon Sunatori",
"Sushruta",
"Theodor Svedberg",
"Joseph Swan",
"Robert Swanson",
"Remi Swierczek",
"Andrei Sychra",
"Vladimir Syromyatnikov",
"Simon Sze",
"Leó Szilárd",
"Muhammad Salih Tahtawi",
"Gyula Takátsy",
"Esther Takeuchi",
"Igor Tamm",
"Ching W. Tang",
"Mardi bin Ali al-Tarsusi",
"Gustav Tauschek",
"Kenyon Taylor",
"Bernard Tellegen",
"Edward Teller",
"Eli Terry",
"Nikola Tesla",
"Léon Theremin",
"Charles Xavier Thomas de Colmar",
"Elihu Thomson",
"William Thomson",
"Eric Tigerstedt",
"Kalman Tihanyi",
"Mikhail Tikhonravov",
"Gavriil Adrianovich Tikhov",
"Benjamin Chew Tilghman",
"Fedor Tokarev",
"Ray Tomlinson",
"Evangelista Torricelli",
"Alfred Traeger",
"Richard Trevithick",
"Franc Trkman",
"Hans Tropsch",
"Yuri Trutnev",
"Roger Y. Tsien",
"Konstantin Tsiolkovsky",
"Mikhail Tsvet",
"Alexei Tupolev",
"Andrei Tupolev",
"Nasīr al-Dīn al-Tūsī",
"Sharaf al-Dīn al-Tūsī",
"Shintaro Uda",
"Lewis Urry",
"Tomislav Uzelac",
"Ira Van Gieson",
"Theophilus Van Kannel",
"Vladimir Veksler",
"John Venn",
"Auguste Victor Louis Verneuil",
"Pierre Vernier",
"Lucien Vidi",
"Edgar Villchur",
"Artturi Ilmari Virtanen",
"Alessandro Volta",
"Bernard Vonnegut",
"Ivan Vučetić",
"Paul Walden",
"Jimmy Wales",
"Madam C.J. Walker",
"Barnes Wallis",
"Ruth Graves Wakefield",
"Frederick Walton",
"Aldred Scott Warthin",
"Robert Watson-Watt",
"James Watt",
"Thomas Wedgwood",
"Carl Auer von Welsbach",
"Jonas Wenström",
"George Westinghouse",
"Charles Wheatstone",
"Richard T. Whitcomb",
"Eli Whitney",
"Frank Whittle",
"Otto Wichterle",
"Norman Wilkinson",
"Charles Thomson Rees Wilson",
"Paul Winchell",
"Sergei Winogradsky",
"Niklaus Wirth",
"A. Baldwin Wood",
"Norman Joseph Woodland",
"Granville Woods",
"James Homer Wright",
"Wright brothers",
"Arthur Wynne",
"Yi Xing",
"Pavel Yablochkov",
"Hidetsugu Yagi",
"Alexander Yakovlev",
"Linus Yale, Jr.",
"Linus Yale, Sr.",
"Shunpei Yamazaki",
"Gazi Yasargil",
"Ryōichi Yazu",
"Gunpei Yokoi",
"Arthur M. Young",
"Vladimir Yourkevitch",
"Tu Youyou",
"Sergei Yudin",
"Muhammad Yunus",
"Abu Yusuf Yaqub",
"Abraham Albert Yuzpe",
"Abu al-Qasim al-Zahrawi",
"Frank Zamboni",
"Giuseppe Zamboni",
"Ludwik Łazarz Zamenhof",
"Walter Zapp",
"Abū Ishāq Ibrāhīm al-Zarqālī",
"Yevgeny Zavoisky",
"Nikolay Zelinsky",
"Ferdinand von Zeppelin",
"Frits Zernike",
"Tang Zhongming",
"Jian Zhou",
"Nikolai Zhukovsky",
"Karl Ziegler",
"Franz Ziehl",
"Konrad Zuse",
"Vasily Zvyozdochkin",
"Louis Agassiz",
"Maria Gaetana Agnesi",
"Al-Battani",
"Abu Nasr Al-Farabi",
"Jim Al-Khalili",
"Muhammad ibn Musa al-Khwarizmi",
"Mihailo Petrovic Alas",
"Angel Alcala",
"Salim Ali",
"Luis Alvarez",
"Andre Marie Ampère",
"Anaximander",
"Mary Anning",
"Virginia Apgar",
"Archimedes",
"Agnes Arber",
"Aristarchus",
"Aristotle",
"Svante Arrhenius",
"Oswald Avery",
"Amedeo Avogadro",
"Avicenna",
"Charles Babbage",
"Francis Bacon",
"Alexander Bain",
"John Logie Baird",
"Joseph Banks",
"Ramon Barba",
"John Bardeen",
"Ibn Battuta",
"William Bayliss",
"George Beadle",
"Arnold Orville Beckman",
"Henri Becquerel",
"Emil Adolf Behring",
"Alexander Graham Bell",
"Emile Berliner",
"Claude Bernard",
"Timothy John Berners-Lee",
"Daniel Bernoulli",
"Jacob Berzelius",
"Henry Bessemer",
"Hans Bethe",
"Homi Jehangir Bhabha",
"Alfred Binet",
"Clarence Birdseye",
"Kristian Birkeland",
"Elizabeth Blackwell",
"Alfred Blalock",
"Katharine Burr Blodgett",
"Franz Boas",
"David Bohm",
"Aage Bohr",
"Niels Bohr",
"Ludwig Boltzmann",
"Max Born",
"Carl Bosch",
"Robert Bosch",
"Jagadish Chandra Bose",
"Satyendra Nath Bose",
"Walther Wilhelm Georg Bothe",
"Robert Boyle",
"Lawrence Bragg",
"Tycho Brahe",
"Brahmagupta",
"Georg Brandt",
"Wernher Von Braun",
"Louis de Broglie",
"Alexander Brongniart",
"Robert Brown",
"Michael E. Brown",
"Lester R. Brown",
"Eduard Buchner",
"William Buckland",
"Georges-Louis Leclerc, Comte de Buffon",
"Robert Bunsen",
"Luther Burbank",
"Jocelyn Bell Burnell",
"Macfarlane Burnet",
"Thomas Burnet",
"Benjamin Cabrera",
"Santiago Ramon y Cajal",
"Rachel Carson",
"George Washington Carver",
"Henry Cavendish",
"Anders Celsius",
"James Chadwick",
"Subrahmanyan Chandrasekhar",
"Erwin Chargaff",
"Noam Chomsky",
"Steven Chu",
"Leland Clark",
"Arthur Compton",
"Nicolaus Copernicus",
"Gerty Theresa Cori",
"Charles-Augustin de Coulomb",
"Jacques Cousteau",
"Brian Cox",
"Francis Crick",
"Nicholas Culpeper",
"Marie Curie",
"Pierre Curie",
"Georges Cuvier",
"Adalbert Czerny",
"Gottlieb Daimler",
"John Dalton",
"James Dwight Dana",
"Charles Darwin",
"Humphry Davy",
"Peter Debye",
"Max Delbruck",
"Jean Andre Deluc",
"René Descartes",
"Rudolf Christian Karl Diesel",
"Paul Dirac",
"Prokop Divis",
"Theodosius Dobzhansky",
"Frank Drake",
"K. Eric Drexler",
"Arthur Eddington",
"Thomas Edison",
"Paul Ehrlich",
"Albert Einstein",
"Gertrude Elion",
"Empedocles",
"Eratosthenes",
"Euclid",
"Leonhard Euler",
"Michael Faraday",
"Pierre de Fermat",
"Enrico Fermi",
"Richard Feynman",
"Fibonacci – Leonardo of Pisa",
"Emil Fischer",
"Ronald Fisher",
"Alexander Fleming",
"Henry Ford",
"Lee De Forest",
"Dian Fossey",
"Leon Foucault",
"Benjamin Franklin",
"Rosalind Franklin",
"Sigmund Freud",
"Galen",
"Galileo Galilei",
"Francis Galton",
"Luigi Galvani",
"George Gamow",
"Carl Friedrich Gauss",
"Murray Gell-Mann",
"Sophie Germain",
"Willard Gibbs",
"William Gilbert",
"Sheldon Lee Glashow",
"Robert Goddard",
"Maria Goeppert-Mayer",
"Thomas Gold",
"Jane Goodall",
"Stephen Jay Gould",
"Fritz Haber",
"Ernst Haeckel",
"Otto Hahn",
"Albrecht von Haller",
"Edmund Halley",
"Thomas Harriot",
"William Harvey",
"Stephen Hawking",
"Otto Haxel",
"Werner Heisenberg",
"Hermann von Helmholtz",
"Jan Baptist von Helmont",
"Joseph Henry",
"William Herschel",
"Gustav Ludwig Hertz",
"Heinrich Hertz",
"Karl F. Herzfeld",
"Antony Hewish",
"David Hilbert",
"Maurice Hilleman",
"Hipparchus",
"Hippocrates",
"Shintaro Hirase",
"Dorothy Hodgkin",
"Robert Hooke",
"Frederick Gowland Hopkins",
"William Hopkins",
"Grace Murray Hopper",
"Frank Hornby",
"Jack Horner",
"Bernardo Houssay",
"Fred Hoyle",
"Edwin Hubble",
"Alexander von Humboldt",
"Zora Neale Hurston",
"James Hutton",
"Christiaan Huygens",
"Ernesto Illy",
"Ernst Ising",
"Keisuke Ito",
"Mae Carol Jemison",
"Edward Jenner",
"J. Hans D. Jensen",
"Irene Joliot-Curie",
"James Prescott Joule",
"Percy Lavon Julian",
"Michio Kaku",
"Heike Kamerlingh Onnes",
"Friedrich August Kekulé",
"Frances Kelsey",
"Pearl Kendrick",
"Johannes Kepler",
"Abdul Qadeer Khan",
"Omar Khayyam",
"Alfred Kinsey",
"Gustav Kirchoff",
"Robert Koch",
"Emil Kraepelin",
"Thomas Kuhn",
"Stephanie Kwolek",
"Jean-Baptiste Lamarck",
"Hedy Lamarr",
"Edwin Herbert Land",
"Karl Landsteiner",
"Pierre-Simon Laplace",
"Max von Laue",
"Antoine Lavoisier",
"Ernest Lawrence",
"Henrietta Leavitt",
"Antonie van Leeuwenhoek",
"Inge Lehmann",
"Gottfried Leibniz",
"Georges Lemaître",
"Leonardo da Vinci",
"Niccolo Leoniceno",
"Aldo Leopold",
"Rita Levi-Montalcini",
"Claude Levi-Strauss",
"Willard Frank Libby",
"Justus von Liebig",
"Carolus Linnaeus",
"Joseph Lister",
"John Locke",
"Hendrik Antoon Lorentz",
"Konrad Lorenz",
"Ada Lovelace",
"Lucretius",
"Charles Lyell",
"Trofim Lysenko",
"Ernst Mach",
"Marcello Malpighi",
"Jane Marcet",
"Guglielmo Marconi",
"Lynn Margulis",
"James Clerk Maxwell",
"Ernst Mayr",
"Barbara McClintock",
"Lise Meitner",
"Gregor Mendel",
"Dmitri Mendeleev",
"Franz Mesmer",
"Antonio Meucci",
"Albert Abraham Michelson",
"Thomas Midgeley Jr.",
"Maria Mitchell",
"Mario Molina",
"Thomas Hunt Morgan",
"Henry Moseley",
"Ukichiro Nakaya",
"John Napier",
"John Needham",
"John von Neumann",
"Thomas Newcomen",
"Isaac Newton",
"Florence Nightingale",
"Tim Noakes",
"Alfred Nobel",
"Emmy Noether",
"Christiane Nusslein-Volhard",
"Bill Nye",
"Hans Christian Oersted",
"Georg Ohm",
"J. Robert Oppenheimer",
"Wilhelm Ostwald",
"Blaise Pascal",
"Louis Pasteur",
"Wolfgang Ernst Pauli",
"Linus Pauling",
"Randy Pausch",
"Ivan Pavlov",
"Marguerite Perey",
"Jean Piaget",
"Philippe Pinel",
"Max Planck",
"Pliny the Elder",
"Karl Popper",
"Beatrix Potter",
"Joseph Priestley",
"Claudius Ptolemy",
"Pythagoras",
"Harriet Quimby",
"Thabit ibn Qurra",
"C. V. Raman",
"Srinivasa Ramanujan",
"William Ramsay",
"John Ray",
"Prafulla Chandra Ray",
"Francesco Redi",
"Sally Ride",
"Bernhard Riemann",
"Wilhelm Röntgen",
"Hermann Rorschach",
"Ronald Ross",
"Ibn Rushd",
"Ernest Rutherford",
"Carl Sagan",
"Mohammad Abdus Salam",
"Jonas Salk",
"Frederick Sanger",
"Alberto Santos-Dumont",
"Walter Schottky",
"Erwin Schrödinger",
"Theodor Schwann",
"Glenn Seaborg",
"Hans Selye",
"Charles Sherrington",
"Gene Shoemaker",
"Ernst Werner von Siemens",
"George Gaylord Simpson",
"B. F. Skinner",
"William Smith",
"Frederick Soddy",
"Arnold Sommerfeld",
"Nettie Stevens",
"William John Swainson",
"Leo Szilard",
"Niccolo Tartaglia",
"Edward Teller",
"Nikola Tesla",
"Thales of Miletus",
"Benjamin Thompson",
"J. J. Thomson",
"William Thomson",
"Henry David Thoreau",
"Kip S. Thorne",
"Clyde Tombaugh",
"Evangelista Torricelli",
"Charles Townes",
"Alan Turing",
"Neil deGrasse Tyson",
"Harold Urey",
"Craig Venter",
"Vladimir Vernadsky",
"Andreas Vesalius",
"Rudolf Virchow",
"Artturi Virtanen",
"Alessandro Volta",
"George Wald",
"Alfred Russel Wallace",
"James Watson",
"James Watt",
"Alfred Wegener",
"John Archibald Wheeler",
"Maurice Wilkins",
"Thomas Willis",
"E. O. Wilson",
"Sven Wingqvist",
"Sergei Winogradsky",
"Friedrich Wöhler",
"Wilbur and Orville Wright",
"Wilhelm Wundt",
"Chen-Ning Yang",
"Ahmed Zewail",
"Vladimir Zworykin"
}
return inventors
